INSERT INTO Roles (Name) VALUES ('Admin'), ('User');
-- Password hashes are generated by the ASP.NET seed. Use EF seed for login-ready users.
INSERT INTO Locations (Name, Address, Phone, OpeningHours, Latitude, Longitude) VALUES
('BrewPoint F-6 Markaz', 'Street 30, F-6 Markaz, Islamabad', '+92 51 111 276 001', '7:00 AM - 11:00 PM', 33.7294, 73.0757),
('BrewPoint Blue Area', 'Jinnah Avenue, Blue Area, Islamabad', '+92 51 111 276 002', '7:00 AM - 12:00 AM', 33.7077, 73.0498),
('BrewPoint I-8 Markaz', 'I-8 Markaz, Islamabad', '+92 51 111 276 003', '8:00 AM - 11:00 PM', 33.6685, 73.0752),
('BrewPoint Bahria Town Phase 7', 'Bahria Town Phase 7, Islamabad', '+92 51 111 276 004', '8:00 AM - 1:00 AM', 33.5165, 73.1050);
INSERT INTO Coffees (Name, Description, Price, Category, SizeOptions, ImageUrl, Ingredients, Calories, IsFeatured, IsAvailable) VALUES
('Islamabad Iced Latte', 'Cold espresso, milk, and a clean city-break finish.', 640, 'Iced', 'Small,Medium,Large', '/assets/generated/coffee-iced-latte.png', 'Espresso,Milk,Ice', 180, 1, 1),
('Pink Cloud Mocha', 'Silky mocha with pink vanilla foam.', 760, 'Mocha', 'Small,Medium,Large', '/assets/generated/coffee-pink-cloud-mocha.png', 'Espresso,Cocoa,Vanilla Foam', 310, 1, 1),
('Classic Americano', 'Bold espresso stretched with hot water.', 420, 'Black', 'Small,Medium,Large', '/assets/generated/coffee-classic-americano.png', 'Espresso,Water', 15, 0, 1),
('Saffron Cappuccino', 'Cappuccino with warm saffron aromatics.', 720, 'Hot', 'Small,Medium,Large', '/assets/generated/coffee-saffron-cappuccino.png', 'Espresso,Milk,Saffron', 220, 1, 1),
('Vanilla Cold Brew', 'Slow-steeped cold brew with vanilla.', 680, 'Cold Brew', 'Small,Medium,Large', '/assets/generated/coffee-vanilla-cold-brew.png', 'Cold Brew,Vanilla', 140, 0, 1),
('Salted Caramel Latte', 'Caramel latte with a salted snap.', 740, 'Latte', 'Small,Medium,Large', '/assets/generated/coffee-salted-caramel-latte.png', 'Espresso,Milk,Caramel,Salt', 330, 1, 1),
('Espresso Shot', 'A compact, high-clarity espresso.', 340, 'Espresso', 'Single,Double', '/assets/generated/coffee-espresso-shot.png', 'Espresso', 5, 0, 1),
('Honey Cinnamon Flat White', 'Flat white with honey and cinnamon.', 700, 'Flat White', 'Small,Medium,Large', '/assets/generated/coffee-honey-cinnamon-flat-white.png', 'Espresso,Milk,Honey,Cinnamon', 260, 0, 1),
('Rose Pistachio Latte', 'A fragrant latte with rose and pistachio.', 780, 'Latte', 'Small,Medium,Large', '/assets/generated/coffee-rose-pistachio.png', 'Espresso,Milk,Rose,Pistachio', 340, 1, 1),
('Dark Chocolate Mocha', 'Deep cocoa, espresso, and steamed milk.', 730, 'Mocha', 'Small,Medium,Large', '/assets/generated/coffee-dark-mocha.png', 'Espresso,Dark Chocolate,Milk', 320, 0, 1),
('Hazelnut Macchiato', 'Layered espresso with hazelnut sweetness.', 690, 'Macchiato', 'Small,Medium,Large', '/assets/generated/coffee-hazelnut-macchiato.png', 'Espresso,Milk,Hazelnut', 250, 0, 1),
('Midnight Black Brew', 'Dark, clean, late-night filter coffee.', 520, 'Brewed', 'Small,Medium,Large', '/assets/generated/coffee-midnight-black-brew.png', 'Filter Coffee', 10, 1, 1);
